apiv1/urls.py
from django.urls import path
from apiv1.views import AvailableClassesListAPIView, StudentsFromClassAPIView, MyInfoAPIView, SchoolUpdateAPIView


urlpatterns = [
    path('classes/', AvailableClassesListAPIView.as_view()),
    path('classes/<uuid:class_id>/students/', StudentsFromClassAPIView.as_view()),
    path('auth/me/', MyInfoAPIView.as_view()),
    path('school/', SchoolUpdateAPIView.as_view()),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from school.views import DashboardReactView
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', DashboardReactView.as_view(), name='dashboard_react'),
    path('accounts/', include('accounts.urls')),
    path('school/', include('school.urls', namespace='school')),
    path('student/', include('student.urls', namespace='student')),
    path('api/v1/', include('apiv1.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

school/urls.py
from django.urls import path
from school import views

app_name = 'school'

urlpatterns = [
    path('create/', views.CreateSchoolView.as_view(), name='create_school'),
    path('update/<uuid:pk>/', views.UpdateSchoolView.as_view(), name='update_school'),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('class/create/', views.ClassCreateView.as_view(), name="class_create"),
    path('class/<uuid:pk>/', views.ClassDetailView.as_view(), name="class_detail"),
    path('class/add-teacher-not-public/<uuid:id>/', views.class_add_teacher_handler, name="add_teacher"),
    path('update-classes-not-public/<uuid:school_id>', views.increase_classes_number_handler, name="increase_class"),
]

student/urls.py
from django.urls import path

from student.views import UploadStudentsExcelView

app_name = 'student'

urlpatterns = [
    path('upload/<uuid:class_id>/', UploadStudentsExcelView.as_view(), name='upload'),
]

templates/class/create.html
{% extends '_base.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container">
    <form class="col-6 offset-3" method="POST" enctype="multipart/form-data">
    <h1>New Class</h1>
    {% csrf_token %}
    <div class="my-3">
        {{ form.name.label_tag }}
        {% render_field form.name class="form-control" %}
        {% if form.errors.name %}
            {{ form.errors.name }}
        {% endif %}

    </div>
    <input type="submit" value="Submit" class="btn btn-primary">
</form>
</div>
{% endblock %}

templates/class/detail.html
{% extends "_base.html" %}
{% load widget_tweaks %}

{% block title %}{{ class.name }}{% endblock %}

{% block content %}

    <div class="container">
        <div>
            <h1>{{ class.name }}</h1>
        </div>

        {% if is_admin %}
            <div>
                <h3>Teachers</h3>
                <ul class="list-group col-3">

                    {% for teacher in class.teachers.all %}
                        <li class="list-group-item">{{ teacher.first_name }} {{ teacher.last_name }}</li>
                    {% endfor %}
                    <button class="list-group-item list-group-item-action list-group-item-success"
                            data-bs-toggle="modal" data-bs-target="#exampleModal">Manage Teachers
                    </button>
                </ul>
            </div>
            <a href="{% url 'student:upload' class.id %}">Upload Excel</a>
            <div class="mt-2">
                <h3>Students</h3>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Email</th>
                            <th>Phone Number</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for student in students %}
                        <tr>
                            <td>{{ student.order_in_class }}</td>
                            <td>{{ student.first_name }}</td>
                            <td>{{ student.last_name }}</td>
                            <td>{{ student.email }}</td>
                            <td>{{ student.phone_number }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            </div>

            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                 aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Manage Teachers</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <form action="{% url 'school:add_teacher' class.id %}" method="POST">
                            <div class="modal-body">
                                {% csrf_token %}
                                {{ add_teacher_form.teachers.label_tag }}
                                {% render_field add_teacher_form.teachers class="form-control" %}
                                <small class="text-muted">Use Control/Command to select</small>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-primary">Save changes</button>
                            </div>

                        </form>
                    </div>
                </div>
            </div>

        {% endif %}

{% endblock %}