apiv1/urls.py
from django.urls import path
from apiv1.views import AvailableClassesListAPIView, StudentsFromClassAPIView, MyInfoAPIView, SchoolUpdateAPIView


urlpatterns = [
    path('classes/', AvailableClassesListAPIView.as_view()),
    path('classes/<uuid:class_id>/students/', StudentsFromClassAPIView.as_view()),
    path('auth/me/', MyInfoAPIView.as_view()),
    path('school/', SchoolUpdateAPIView.as_view()),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from school.views import DashboardReactView
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', DashboardReactView.as_view(), name='dashboard_react'),
    path('accounts/', include('accounts.urls')),
    path('school/', include('school.urls', namespace='school')),
    path('student/', include('student.urls', namespace='student')),
    path('api/v1/', include('apiv1.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

school/urls.py
from django.urls import path
from school import views

app_name = 'school'

urlpatterns = [
    path('create/', views.CreateSchoolView.as_view(), name='create_school'),
    path('update/<uuid:pk>/', views.UpdateSchoolView.as_view(), name='update_school'),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('class/create/', views.ClassCreateView.as_view(), name="class_create"),
    path('class/<uuid:pk>/', views.ClassDetailView.as_view(), name="class_detail"),
    path('class/add-teacher-not-public/<uuid:id>/', views.class_add_teacher_handler, name="add_teacher"),
    path('update-classes-not-public/<uuid:school_id>', views.increase_classes_number_handler, name="increase_class"),
]

templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
    {% block scripts %}
    
    {% endblock %}
    <title>{% block title %}SchManSys{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'profile' %}">Profile</a>
                    </li>
                    {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            Sign Up
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item" href="{% url 'sign_up_admin' %}">As Administration</a></li>
                            <li><a class="dropdown-item" href="{% url 'sign_up_teacher' %}">As Teacher</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'school:dashboard' %}">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <span>{{ user.username }}</span>
        </div>
    </nav>
    {% block content %}

    {% endblock %}
    {% include 'shared/messages.html' %}

</body>
</html>

templates/school_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <input type="submit" name="Submit">
</form>
</body>
</html>

templates/school_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>Are you sure you want to delete "{{ item }}"?</p>
<form action="{% url 'school-delete' item.id %}" method="POST">
    {% csrf_token %}
    <a href="/">Cancel</a>

    <input type="submit" value="Submit">
</form>
</body>
</html>

templates/school_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="{% url 'school-create' %}">Create</a>

{% for item in list %}
<ul>{{ item }} <a href="{% url 'school-update' item.id %}">update</a>, <a href="{% url 'school-delete' item.id %}">Delete</a></ul>
{% endfor %}

</body>
</html>

templates/school_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <input type="submit" name="Submit">
</body>
</html>