apiv1/urls.py
from django.urls import path
from apiv1.views import AvailableClassesListAPIView, StudentsFromClassAPIView, MyInfoAPIView, SchoolUpdateAPIView


urlpatterns = [
    path('classes/', AvailableClassesListAPIView.as_view()),
    path('classes/<uuid:class_id>/students/', StudentsFromClassAPIView.as_view()),
    path('auth/me/', MyInfoAPIView.as_view()),
    path('school/', SchoolUpdateAPIView.as_view()),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from school.views import DashboardReactView
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', DashboardReactView.as_view(), name='dashboard_react'),
    path('accounts/', include('accounts.urls')),
    path('school/', include('school.urls', namespace='school')),
    path('student/', include('student.urls', namespace='student')),
    path('api/v1/', include('apiv1.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

school/urls.py
from django.urls import path
from school import views

app_name = 'school'

urlpatterns = [
    path('create/', views.CreateSchoolView.as_view(), name='create_school'),
    path('update/<uuid:pk>/', views.UpdateSchoolView.as_view(), name='update_school'),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('class/create/', views.ClassCreateView.as_view(), name="class_create"),
    path('class/<uuid:pk>/', views.ClassDetailView.as_view(), name="class_detail"),
    path('class/add-teacher-not-public/<uuid:id>/', views.class_add_teacher_handler, name="add_teacher"),
    path('update-classes-not-public/<uuid:school_id>', views.increase_classes_number_handler, name="increase_class"),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models
from school.models import School


class CustomUser(AbstractUser):

    class Roles(models.IntegerChoices):

        TEACHER = 0, 'Teacher'
        ADMIN_MEMBER = 1, 'Administration Member'

    email_verified = models.BooleanField(default=False)
    role = models.IntegerField(choices=Roles.choices, default=0)
    school = models.ForeignKey(School, on_delete=models.SET_NULL,
                               null=True,
                               blank=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class TeacherManager(UserManager):

    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(role=CustomUser.Roles.TEACHER)


class AdminMemberManager(UserManager):

    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(role=CustomUser.Roles.ADMIN_MEMBER)


class Teacher(CustomUser):

    objects = TeacherManager()

    def save(self, *args, **kwargs):
        """Setting teacher role to model on create"""
        if not self.pk:
            self.role = CustomUser.Roles.TEACHER

        super(Teacher, self).save(*args, **kwargs)

    class Meta:
        proxy = True


class AdministrationMember(CustomUser):

    objects = AdminMemberManager()

    def save(self, *args, **kwargs):
        """Setting admin-member role to model on create"""
        if not self.pk:
            self.role = CustomUser.Roles.ADMIN_MEMBER
        super(AdministrationMember, self).save(*args, **kwargs)

    class Meta:
        proxy = True

school/models.py
import re
import uuid
from django.db import models
from django.urls import reverse


class School(models.Model):
    id = models.UUIDField(
         primary_key=True,
         default=uuid.uuid4,
         editable=False)
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    @staticmethod
    def get_by_id(id):
        try:
            return School.objects.get(id=id)
        except School.DoesNotExist:
            return None


class Class(models.Model):

    id = models.UUIDField(
         primary_key=True,
         default=uuid.uuid4,
         editable=False)
    name = models.CharField(max_length=4)
    school = models.ForeignKey(School, on_delete=models.CASCADE, related_name='classes')
    teachers = models.ManyToManyField("accounts.CustomUser", related_name="classes", blank=True)

    def __str__(self):
        return self.name

    class Meta:
        unique_together = ("school", "name")

    def add_teachers(self, *teachers):
        self.teachers.add(*teachers)
        self.save()

    def increase_class_number(self):
        """
            Be careful so that wasn't IntegrityError.
            For this when updating class for example 3-A there mustn't be 4-A in same school.
            If using in loop, order_by name desc
        """
        pattern = r"[0-9]+"
        grade = int(re.search(pattern, self.name).group(0))
        self.name = re.sub(pattern, str(grade + 1), self.name)
        self.save()

    def get_absolute_url(self):

        return reverse('school:class_detail', kwargs={"pk": self.id})

    @staticmethod
    def get_by_id(id):
        try:
            return Class.objects.get(id=id)
        except Class.DoesNotExist:
            return None

    @staticmethod
    def order_by_name(queryset, _reverse=False):
        pattern = r"[0-9]+"
        return sorted(queryset, key=lambda cls: int(re.search(pattern, cls.name).group(0)), reverse=_reverse)

school/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.db.models import Q

from accounts.models import Teacher
from school.models import School, Class


class CreateSchoolForm(forms.ModelForm):
    class Meta:
        model = School
        fields = ['name']


class CreateUpdateClassForm(forms.ModelForm):

    class Meta:
        model = Class
        fields = ('name', )

    def __init__(self, school, *args, **kwargs):
        super(CreateUpdateClassForm, self).__init__(*args, **kwargs)
        self.school = school

    def clean_name(self):
        name = self.cleaned_data['name']
        if Class.objects.filter(Q(name=name) & Q(school=self.school)).exists():
            self.add_error('name', ValidationError("Class " + name + " already exists"))
        return name


class AddTeacherClassForm(forms.ModelForm):

    def __init__(self, school=None, *args, **kwargs):
        super(AddTeacherClassForm, self).__init__(*args, **kwargs)
        if school:
            self.fields['teachers'].queryset = Teacher.objects.filter(school=school)

    class Meta:
        model = Class
        fields = ('teachers', )

school/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import Http404
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.decorators.http import require_http_methods
from django.views.generic import CreateView, UpdateView, DetailView, TemplateView

from accounts.models import CustomUser
from school.forms import CreateUpdateClassForm, AddTeacherClassForm
from school.models import Class
from school.models import School
from school.permissions import admin_required


# School Views


class CreateSchoolView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = School
    fields = ['name']
    template_name = 'school/create_school.html'
    success_url = reverse_lazy('school:dashboard')
    login_url = reverse_lazy('login')

    def has_permission(self):
        user = self.request.user
        return user.role == CustomUser.Roles.ADMIN_MEMBER and user.school is None

    def form_valid(self, form):
        response = super(CreateSchoolView, self).form_valid(form)
        self.request.user.school = self.object
        self.request.user.save()
        return response


class UpdateSchoolView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = School
    fields = ['name']
    template_name = 'school/update_school.html'
    success_url = reverse_lazy('school:dashboard')
    login_url = reverse_lazy('login')

    def has_permission(self):
        return self.request.user.school == self.get_object() \
               and self.request.user.role == CustomUser.Roles.ADMIN_MEMBER


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'school/dashboard.html'
    login_url = reverse_lazy('login')

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        context['is_admin'] = self.request.user.role == CustomUser.Roles.ADMIN_MEMBER
        if self.request.user.school is None:
            context['school'] = None
            return context

        context['school'] = self.request.user.school
        if self.request.user.role == CustomUser.Roles.ADMIN_MEMBER:
            context['classes'] = Class.order_by_name(self.request.user.school.classes.all())
        if self.request.user.role == CustomUser.Roles.TEACHER:
            context['classes'] = Class.order_by_name(self.request.user.classes.all())
        return context


class DashboardReactView(TemplateView):

    template_name = 'index.html'


# Class View

class ClassCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Class
    login_url = reverse_lazy('login')
    template_name = "class/create.html"
    form_class = CreateUpdateClassForm

    def has_permission(self):
        """Checking whether user belongs to any school. No matter user is teacher or admin"""
        return self.request.user.school is not None

    def get_form_kwargs(self):
        kwargs = super(ClassCreateView, self).get_form_kwargs()
        kwargs['school'] = self.request.user.school
        return kwargs

    def form_valid(self, form):
        """Adding school to newly created class and adding teacher if teacher creates class"""
        new_class = form.save(commit=False)
        new_class.school = self.request.user.school
        new_class.save()
        messages.success(self.request, f'New class {new_class.name} successfully created')
        if self.request.user.role == CustomUser.Roles.TEACHER:
            new_class.add_teachers(self.request.user)
        return super(ClassCreateView, self).form_valid(form)


class ClassDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):

    model = Class
    login_url = reverse_lazy('login')
    template_name = 'class/detail.html'
    context_object_name = "class"

    def has_permission(self):
        """Can access if user in Class.teachers or it is admin and Class.school==user.school"""
        if self.request.user in self.get_object().teachers.all():
            return True
        if self.request.user.role == CustomUser.Roles.ADMIN_MEMBER and \
                self.get_object().school == self.request.user.school:
            return True
        return False

    def get_context_data(self, **kwargs):
        context = super(ClassDetailView, self).get_context_data(**kwargs)
        context['is_admin'] = self.request.user.role == CustomUser.Roles.ADMIN_MEMBER
        context['add_teacher_form'] = AddTeacherClassForm(school=self.get_object().school, instance=self.get_object())
        context['students'] = self.object.students.all()
        return context


@require_http_methods(['POST'])
@admin_required(login_url=reverse_lazy('login'))
def class_add_teacher_handler(request, id):
    _class = Class.get_by_id(id)
    if not _class:
        raise Http404()
    form = AddTeacherClassForm(_class.school, request.POST, instance=_class)
    if form.is_valid():
        form.save()
    return redirect(reverse('school:class_detail', kwargs={'pk': id}))


@require_http_methods(['POST'])
@admin_required(login_url=reverse_lazy('login'))
def increase_classes_number_handler(request, school_id):
    school = School.get_by_id(school_id)
    if not school:
        raise Http404()
    # TODO: change sorting
    # the -name working not correct with 9 and 10 for example
    classes = Class.order_by_name(school.classes.all(), True)
    for _class in classes:
        _class.increase_class_number()
    messages.success(request, 'All classes\' names updated')
    return redirect(reverse('school:dashboard'))

templates/school/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <input type="submit" name="Submit">
</form>
</body>
</html>

templates/school/create_school.html
{% extends '_base.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container">
    <form class="col-6 offset-3" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="my-3">
        {{ form.name.label_tag }}
        {% render_field form.name class="form-control"  %}
    </div>
    <input type="submit" value="Submit" class="btn btn-primary">
</form>
</div>
{% endblock %}

templates/school/dashboard.html
{% extends '_base.html' %}
{% block content %}
<div class="p-3 mb-4 rounded-3">
    <div>
        {{ user.first_name }} {{ user.last_name }} | {{ user.get_role_display }}
    </div>
</div>
<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">

        {% if school %}
            <h1 class="display-5 fw-bold float-start">{{ school.name }}</h1>
        {% else %}
            {% if is_admin %}
                <h1><a href="{% url 'school:create_school' %}">Add your school</a></h1>
            {% endif %}
        {% endif %}
        {% if is_admin and school %}
            <form action="{% url 'school:increase_class' school.id %}" class="float-end" method="POST">
                {% csrf_token %}
                <div class="btn-group">
                    <a class="btn btn-primary float-end" href="{% url 'school:update_school' school.id %}">Update</a>
                    {# TODO: give sensible name to button below #}
                    <button type="submit" class="btn btn-primary" data-bs-toggle="tooltip"
                            data-bs-placement="top" title="Increase each class name by 1">+ Classes</button>
                </div>
            </form>
        {% endif %}
    </div>
</div>
<div class="row mx-2">
    <div class="list-group list-group-flush col-5">
        {% for class in classes %}
            <a href="{{ class.get_absolute_url }}"
               class="list-group-item list-group-item-action">{{ class.name }}</a>
        {% empty %}
            <li class="list-group-item">No classes available</li>
            <a href="{% url 'school:class_create' %}" class="list-group-item list-group-item-action active">Create
                class</a>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/school/update.html
{% extends '_base.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container">
    <form class="col-6 offset-3" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="my-3">
        {{ form.name.label_tag }}
        {% render_field form.name class="form-control" %}
    </div>
    <input type="submit" value="Submit" class="btn btn-primary">
</form>
</div>
{% endblock %}

templates/school/update_school.html
{% extends '_base.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container">
    <form class="col-6 offset-3" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="my-3">
        {{ form.name.label_tag }}
        {% render_field form.name class="form-control" %}
    </div>
    <input type="submit" value="Submit" class="btn btn-primary">
</form>
</div>
{% endblock %}